baseURL: "https://pejmanghafouri.github.io/"
theme: "hyde-hyde"
publishDir: "docs"

DefaultContentLanguage: en
languages:
  fa:
    languageCode: "fa-ir"
    languageName: "فا"
    title: "پژمان غفوری"
    languagedirection: rtl
    layoutReverse: true
    weight: 2
    menus:
      main:
      - name: "رزومه"
        weight: 200
        url: "/resume/"
        identifier: "resume"
      - name: "تماس"
        weight: 250
        url: "/contact/"
        identifier: "contact"
    params:
      author: "پژمان غفوری"
      title: "وبلاگ شخصی پژمان غفوری"
      description: |
        Fullstack Developer
        ____________________
        همراه: 09351869434
        سربازی: معاف از خدمت
        سن: 26
        
  en:
    languageCode: "en-us"
    languageName: "en"
    title: "Pejman Ghafouri"
    weight: 1
    menus:
      main:
      - name: "My Resume"
        weight: 200
        url: "/resume/"
        identifier: "resume"
      - name: "Contact Me"
        weight: 250
        url: "/contact/"
        identifier: "contact"
    params:
      author: "Pejman Ghafouri"
      title: "Pejman Ghafouri Personal Blog"
      description: |
        Fullstack Developer
        ____________________
        (+98) 935 186 9434
        Age: 26

params:
  authorimage: "/img/PejmanGhafouri.jpeg"
  mainSections: "posts"
  highlightjs: true
  highlightjsstyle: "github"
  postNavigation: false
  since: "2024"
  copyright: "| Pejman Ghafouri"
  social:
    github: "pejmanghafouri"
    linkedin: "pejman-ghafouri"
    telegram: "pejman_ghafouri"
    email: "pejmanghafouricorp@gmail.com"	

